# Generated by Django 6.0 on 2025-12-26 07:51

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ordre', models.PositiveIntegerField(unique=True, verbose_name="Numéro d'ordre")),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('parti_politique', models.CharField(blank=True, max_length=200, verbose_name='Parti politique')),
                ('est_independant', models.BooleanField(default=False, verbose_name='Candidat indépendant')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'db_table': 'pv_candidat',
                'ordering': ['numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('nombre_inscrits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_votants', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('suffrages_exprimes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bulletins_nuls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bulletins_blancs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_pv_officiel', cloudinary.models.CloudinaryField(max_length=255, verbose_name='pv_officiel')),
                ('photo_tableau_resultats', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='tableau_resultats')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CORRECTION', 'En correction')], default='EN_ATTENTE', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('commentaires_validation', models.TextField(blank=True, null=True)),
                ('has_incoherence', models.BooleanField(default=False)),
                ('erreurs_detectees', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau_vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proces_verbaux', to='geography.bureauvote')),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.checkin')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_soumis', to=settings.AUTH_USER_MODEL)),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procès-verbal',
                'verbose_name_plural': 'Procès-verbaux',
                'db_table': 'proces_verbaux',
                'ordering': ['-date_soumission'],
                'unique_together': {('bureau_vote', 'date_soumission')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VALIDER', 'Valider'), ('REJETER', 'Rejeter'), ('CORRECTION', 'Demander correction')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to='pv.procesverbal')),
            ],
            options={
                'verbose_name': 'Historique de validation',
                'verbose_name_plural': 'Historiques de validation',
                'db_table': 'pv_historique_validation',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='ResultatCandidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_voix', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de voix')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='pv.candidat')),
                ('pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='pv.procesverbal')),
            ],
            options={
                'verbose_name': 'Résultat candidat',
                'verbose_name_plural': 'Résultats candidats',
                'db_table': 'pv_resultat_candidat',
                'ordering': ['-nombre_voix'],
                'unique_together': {('pv', 'candidat')},
            },
        ),
    ]
