# Generated by Django 6.0 on 2025-12-26 07:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format: +225XXXXXXXX ou 225XXXXXXXX', regex='^\\+?225?\\d{8,10}$')])),
                ('matricule', models.CharField(blank=True, help_text="Matricule de l'agent", max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('ADMIN', 'Administrateur'), ('SUPERVISEUR', 'Superviseur')], default='SUPERVISEUR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('bureau_vote', models.ForeignKey(blank=True, help_text="Bureau de vote d'affectation (obligatoire pour superviseur)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superviseurs', to='geography.bureauvote')),
                ('commune', models.ForeignKey(blank=True, help_text="Commune d'affectation (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='geography.commune')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(blank=True, help_text="Département d'affectation (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='geography.departement')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('lieu_vote', models.ForeignKey(blank=True, help_text="Lieu de vote d'affectation (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='geography.lieuvote')),
                ('region', models.ForeignKey(blank=True, help_text="Région d'affectation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='geography.region')),
                ('sous_prefecture', models.ForeignKey(blank=True, help_text="Sous-préfecture d'affectation (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='geography.sousprefecture')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Modification utilisateur'), ('USER_DELETE', 'Suppression utilisateur'), ('PV_SUBMIT', 'Soumission PV'), ('PV_VALIDATE', 'Validation PV'), ('PV_REJECT', 'Rejet PV'), ('INCIDENT_CREATE', 'Création incident'), ('INCIDENT_RESOLVE', 'Résolution incident'), ('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CONFIG_CHANGE', 'Modification configuration'), ('EXPORT', 'Export de données')], max_length=50)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_saisi', models.CharField(help_text='Nom complet saisi lors du check-in (doit correspondre exactement)', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude GPS au moment du check-in', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude GPS au moment du check-in', max_digits=10)),
                ('precision_gps', models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True si le superviseur est actuellement en check-in')),
                ('nom_valide', models.BooleanField(default=False, help_text='True si le nom saisi correspond au nom enregistré')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text="Informations sur l'appareil utilisé")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('distance_bureau', models.FloatField(blank=True, help_text='Distance en mètres entre le check-in et le bureau de vote', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bureau_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='geography.bureauvote')),
                ('superviseur', models.ForeignKey(limit_choices_to={'role': 'SUPERVISEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'db_table': 'checkins',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexions',
                'db_table': 'login_history',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(choices=[('create_user', 'Créer des utilisateurs'), ('edit_user', 'Modifier des utilisateurs'), ('delete_user', 'Supprimer des utilisateurs'), ('view_all_users', 'Voir tous les utilisateurs'), ('submit_pv', 'Soumettre des PV'), ('validate_pv', 'Valider des PV'), ('reject_pv', 'Rejeter des PV'), ('delete_pv', 'Supprimer des PV'), ('export_pv', 'Exporter des PV'), ('create_incident', 'Créer des incidents'), ('assign_incident', 'Assigner des incidents'), ('resolve_incident', 'Résoudre des incidents'), ('close_incident', 'Clôturer des incidents'), ('manage_candidats', 'Gérer les candidats'), ('manage_bureaux', 'Gérer les bureaux de vote'), ('configure_system', 'Configurer le système'), ('view_statistics', 'Voir les statistiques'), ('export_reports', 'Exporter des rapports'), ('view_audit_logs', "Voir les logs d'audit"), ('send_notifications', 'Envoyer des notifications'), ('manage_notifications', 'Gérer les notifications')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de la permission (optionnel)", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, help_text='Limiter la permission à une région spécifique', null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_custom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'user_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['region', 'role'], name='users_region__962146_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['bureau_vote'], name='users_bureau__3cea96_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['matricule'], name='users_matricu_5d6274_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_logs_target__f350f5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['superviseur', 'checkin_time'], name='checkins_supervi_81fb77_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['bureau_vote', 'is_active'], name='checkins_bureau__76b33a_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['is_active', 'checkout_time'], name='checkins_is_acti_463455_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['checkin_time'], name='checkins_checkin_b04bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'login_time'], name='login_histo_user_id_6d3173_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='login_histo_ip_addr_3ce48d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_time'], name='login_histo_login_t_878062_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['user', 'permission_code'], name='user_permis_user_id_b3bb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['permission_code', 'is_active'], name='user_permis_permiss_253e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user', 'permission_code', 'region')},
        ),
    ]
