# Generated by Django 5.0.1 on 2025-12-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_user_id_88267f_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_action_474804_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_target__f350f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_timesta_423be6_idx",
        ),
        migrations.RemoveIndex(
            model_name="checkin",
            name="checkins_supervi_81fb77_idx",
        ),
        migrations.RemoveIndex(
            model_name="checkin",
            name="checkins_bureau__76b33a_idx",
        ),
        migrations.RemoveIndex(
            model_name="checkin",
            name="checkins_is_acti_463455_idx",
        ),
        migrations.RemoveIndex(
            model_name="checkin",
            name="checkins_checkin_b04bf7_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="login_histo_user_id_6d3173_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="login_histo_ip_addr_3ce48d_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="login_histo_login_t_878062_idx",
        ),
        migrations.RemoveIndex(
            model_name="permission",
            name="user_permis_user_id_b3bb3f_idx",
        ),
        migrations.RemoveIndex(
            model_name="permission",
            name="user_permis_permiss_253e2e_idx",
        ),
        migrations.RemoveField(
            model_name="loginhistory",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="loginhistory",
            name="longitude",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_CREATE", "Création utilisateur"),
                    ("USER_UPDATE", "Modification utilisateur"),
                    ("USER_DELETE", "Suppression utilisateur"),
                    ("PV_SUBMIT", "Soumission PV"),
                    ("PV_VALIDATE", "Validation PV"),
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="device_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="distance_bureau",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="nom_saisi",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="nom_valide",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="precision_gps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="permission_code",
            field=models.CharField(
                choices=[
                    ("create_user", "Créer des utilisateurs"),
                    ("edit_user", "Modifier des utilisateurs"),
                    ("delete_user", "Supprimer des utilisateurs"),
                    ("validate_pv", "Valider des PV"),
                    ("export_reports", "Exporter des rapports"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.region",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Région d'affectation (optionnel pour BACK_OFFICE)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="geography.region",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("BACK_OFFICE", "Back Office"),
                    ("SUPER_ADMIN", "Super Administrateur"),
                    ("ADMIN", "Administrateur"),
                    ("SUPERVISEUR", "Superviseur"),
                ],
                default="SUPERVISEUR",
                max_length=20,
            ),
        ),
    ]
