# Generated by Django 6.0 on 2025-12-26 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_departement', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Code invalide')])),
                ('nom_departement', models.CharField(max_length=200)),
                ('chef_lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('population', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'geo_departements',
                'ordering': ['nom_departement'],
            },
        ),
        migrations.CreateModel(
            name='LieuVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_lv', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Code invalide')])),
                ('nom_lv', models.CharField(max_length=200, verbose_name='Nom du lieu de vote')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('type_lieu', models.CharField(choices=[('ECOLE', 'École'), ('MAIRIE', 'Mairie'), ('CENTRE_COMMUNAUTAIRE', 'Centre communautaire'), ('SALLE_POLYVALENTE', 'Salle polyvalente'), ('AUTRE', 'Autre')], default='ECOLE', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude GPS', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude GPS', max_digits=10, null=True)),
                ('est_accessible_pmr', models.BooleanField(default=False, verbose_name='Accessible aux personnes à mobilité réduite')),
                ('nombre_salles', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Lieu de vote',
                'verbose_name_plural': 'Lieux de vote',
                'db_table': 'geo_lieux_vote',
                'ordering': ['code_lv'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_commune', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Code invalide')])),
                ('nom_commune', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=0)),
                ('type_commune', models.CharField(choices=[('URBAINE', 'Urbaine'), ('RURALE', 'Rurale')], default='RURALE', max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='geography.departement')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'geo_communes',
                'ordering': ['nom_commune'],
            },
        ),
        migrations.CreateModel(
            name='BureauVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_bv', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Code invalide')])),
                ('nom_bv', models.CharField(max_length=200, verbose_name='Nom du bureau de vote')),
                ('nombre_inscrits', models.IntegerField(default=0, help_text="Nombre d'électeurs inscrits", validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_ordre', models.IntegerField(default=1, help_text="Numéro d'ordre dans le lieu de vote")),
                ('salle_numero', models.CharField(blank=True, help_text='Numéro ou nom de la salle', max_length=50, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('lieu_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux_vote', to='geography.lieuvote')),
            ],
            options={
                'verbose_name': 'Bureau de vote',
                'verbose_name_plural': 'Bureaux de vote',
                'db_table': 'geo_bureaux_vote',
                'ordering': ['lieu_vote', 'numero_ordre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_region', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Code invalide')])),
                ('nom_region', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=0, help_text='Population totale de la région')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie en km²', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'db_table': 'geo_regions',
                'ordering': ['nom_region'],
                'indexes': [models.Index(fields=['code_region'], name='geo_regions_code_re_dace17_idx'), models.Index(fields=['nom_region'], name='geo_regions_nom_reg_6e0c36_idx')],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='geography.region'),
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_sous_prefecture', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Code invalide')])),
                ('nom_sous_prefecture', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=0)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_prefectures', to='geography.commune')),
            ],
            options={
                'verbose_name': 'Sous-préfecture',
                'verbose_name_plural': 'Sous-préfectures',
                'db_table': 'geo_sous_prefectures',
                'ordering': ['nom_sous_prefecture'],
            },
        ),
        migrations.AddField(
            model_name='lieuvote',
            name='sous_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieux_vote', to='geography.sousprefecture'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['code_commune'], name='geo_commune_code_co_4c9ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['departement', 'nom_commune'], name='geo_commune_departe_c3723f_idx'),
        ),
        migrations.AddIndex(
            model_name='bureauvote',
            index=models.Index(fields=['code_bv'], name='geo_bureaux_code_bv_66115a_idx'),
        ),
        migrations.AddIndex(
            model_name='bureauvote',
            index=models.Index(fields=['lieu_vote', 'numero_ordre'], name='geo_bureaux_lieu_vo_d61097_idx'),
        ),
        migrations.AddIndex(
            model_name='bureauvote',
            index=models.Index(fields=['est_actif'], name='geo_bureaux_est_act_028a9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bureauvote',
            unique_together={('lieu_vote', 'numero_ordre')},
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['code_departement'], name='geo_departe_code_de_493803_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['region', 'nom_departement'], name='geo_departe_region__7cae64_idx'),
        ),
        migrations.AddIndex(
            model_name='sousprefecture',
            index=models.Index(fields=['code_sous_prefecture'], name='geo_sous_pr_code_so_14ee75_idx'),
        ),
        migrations.AddIndex(
            model_name='sousprefecture',
            index=models.Index(fields=['commune', 'nom_sous_prefecture'], name='geo_sous_pr_commune_be981f_idx'),
        ),
        migrations.AddIndex(
            model_name='lieuvote',
            index=models.Index(fields=['code_lv'], name='geo_lieux_v_code_lv_c57cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='lieuvote',
            index=models.Index(fields=['sous_prefecture', 'nom_lv'], name='geo_lieux_v_sous_pr_3a4fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='lieuvote',
            index=models.Index(fields=['latitude', 'longitude'], name='geo_lieux_v_latitud_4455ab_idx'),
        ),
    ]
