# Generated by Django 5.0.1 on 2025-12-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logrefreshstatistique",
            name="cache_statistique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs_refresh",
                to="statistics.cachestatistique",
            ),
        ),
    ]
