# Generated by Django 6.0 on 2025-12-26 07:51

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('categorie', models.CharField(choices=[('ABSENCE_ASSESSEURS', "Absence d'assesseurs"), ('MATERIEL_MANQUANT', 'Matériel manquant'), ('RETARD_OUVERTURE', "Retard d'ouverture"), ('RETARD_FERMETURE', 'Retard de fermeture'), ('PROBLEME_TECHNIQUE', 'Problème technique'), ('INCIDENT_SECURITAIRE', 'Incident sécuritaire'), ('FRAUDE_SUSPECTEE', 'Fraude suspectée'), ('AFFLUENCE_ANORMALE', 'Affluence anormale'), ('PROBLEME_ELECTRICITE', "Problème d'électricité"), ('PROBLEME_ACCES', "Problème d'accès au bureau"), ('CONFLIT', 'Conflit/Altercation'), ('AUTRE', 'Autre')], max_length=30)),
                ('titre_template', models.CharField(max_length=200)),
                ('description_template', models.TextField()),
                ('priorite_defaut', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('impact_defaut', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('nombre_utilisations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Modèle d'incident",
                'verbose_name_plural': "Modèles d'incidents",
                'db_table': 'modeles_incidents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(editable=False, max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('ABSENCE_ASSESSEURS', "Absence d'assesseurs"), ('MATERIEL_MANQUANT', 'Matériel manquant'), ('RETARD_OUVERTURE', "Retard d'ouverture"), ('RETARD_FERMETURE', 'Retard de fermeture'), ('PROBLEME_TECHNIQUE', 'Problème technique'), ('INCIDENT_SECURITAIRE', 'Incident sécuritaire'), ('FRAUDE_SUSPECTEE', 'Fraude suspectée'), ('AFFLUENCE_ANORMALE', 'Affluence anormale'), ('PROBLEME_ELECTRICITE', "Problème d'électricité"), ('PROBLEME_ACCES', "Problème d'accès au bureau"), ('CONFLIT', 'Conflit/Altercation'), ('AUTRE', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('heure_incident', models.DateTimeField()),
                ('impact', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=20)),
                ('vote_affecte', models.BooleanField(default=False)),
                ('nombre_electeurs_impactes', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('TRAITE', 'Traité'), ('CLOS', 'Clos')], default='OUVERT', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_debut_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('actions_menees', models.TextField(blank=True, null=True)),
                ('escalade', models.BooleanField(default=False)),
                ('date_escalade', models.DateTimeField(blank=True, null=True)),
                ('motif_escalade', models.TextField(blank=True, null=True)),
                ('delai_resolution_cible', models.IntegerField(default=240)),
                ('temps_resolution', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_responsable', to=settings.AUTH_USER_MODEL)),
                ('bureau_vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geography.bureauvote')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREER', 'Créer'), ('ATTRIBUER', 'Attribuer'), ('DEMARRER', 'Démarrer traitement'), ('RESOUDRE', 'Résoudre'), ('CLOTURER', 'Clôturer'), ('ESCALADER', 'Escalader')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_incidents', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Historique incident',
                'verbose_name_plural': 'Historiques incidents',
                'db_table': 'incidents_historique',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('est_interne', models.BooleanField(default=False)),
                ('est_lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_incidents', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Message incident',
                'verbose_name_plural': 'Messages incidents',
                'db_table': 'incident_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='incident_photo')),
                ('type_photo', models.CharField(choices=[('PREUVE', "Preuve de l'incident"), ('CONTEXTE', 'Photo de contexte'), ('RESOLUTION', 'Photo de résolution'), ('AUTRE', 'Autre')], default='PREUVE', max_length=20)),
                ('legende', models.CharField(blank=True, max_length=200, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Photo incident',
                'verbose_name_plural': 'Photos incidents',
                'db_table': 'incident_photos',
                'ordering': ['ordre', 'date_prise'],
            },
        ),
    ]
